## Write a Numpy program to compute the multiplication of two given matrixes

In [13]:
import numpy as np

In [4]:
p = [[1, 5], [10, 16]]
q = [[1, 2], [6, 8]]

In [5]:
dotResult = np.dot(p, q)
print(dotResult)

[[ 31  42]
 [106 148]]


## Write a NumPy program to compute the determinant of a given square array

In [18]:
a = np.array([[1, 2],
             [3, 4]])

In [19]:
print(np.linalg.det(a))

-2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [20]:
print(np.cross(p, q))

[ -3 -16]


## Write a NumPy program to compute the condition number of a given matrix

In [21]:
from numpy import linalg as LA

In [22]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print(LA.cond(a))

1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [23]:
print(LA.inv(a))

[[ 0.5  0.   0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
